"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username$directory$git_branch$git_status\
[î‚¶](fg:#D3869B)[$all](fg:#32302f bg:#d3869b bold)[î‚´](fg:#D3869B) \
$time\
\n$os$character
"""

[character]
success_symbol = "[ ï„¸](bold #B8BB26)"
error_symbol = "[ ïª](bold #FB4934)"

[directory]
format = "[î‚¶](fg:#8EC07C)[ïŠ $path](fg:#32302f bg:#8EC07C bold)[î‚´](fg:#8EC07C) "
truncation_length = 3
truncation_symbol = "â€¦/"

[git_branch]
format = "[î‚¶](fg:#FABD2F)[îœ¥](fg:#32302F bg:#FABD2F bold)[î‚´](fg:#FABD2F bg:#32302F)[ $branch](fg:#FABD2F bg:#32302F bold)"
symbol = ""

[git_status]
format = "[ $all_status$ahead_behind](fg:#FABD2F bg:#32302F)[î‚´](fg:#32302F)"
# conflicted = "ğŸ³"
ahead = "ï‚ª "
# behind = "ğŸ˜°"
# diverged = "ğŸ˜µ"
up_to_date = "ï˜"
# untracked = "ğŸ¤·"
stashed = "ó°€¼ "
modified = "ó°·ˆ "
# staged = '[++\($count\)](green)'
# renamed = "ğŸ‘…"
# deleted = "ğŸ—‘"

[line_break]
disabled = true

[lua]
format = "$symbol $version"
symbol = "î˜ "

[os]
format = "[î‚¶](fg:#83A598)[$symbol](fg:#32302f bg:#83A598 bold)[î‚´](fg:#83A598)"
disabled = false

[os.symbols]
Arch = "ïŒƒ "

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#32302F bg:#B8BB26 bold"
format = "[î‚¶](fg:#B8BB26)[ï€— $time]($style)[î‚´](fg:#B8BB26)"

[username]
show_always = false
format = "$user"
disabled = true
